### ISSUE TITLE
Talking to main app

### ISSUE THREAD

**Issue by onlymejosh** [exciting-io/slack-bot-server#1]
Hey guys,

Slack-bot-server is exactly what I've been looking for! Awesome work :)

I'm trying to figure out how I can interact with my main app from inside of slack-bot-server. At the moment I have my code living in `lib/slackbots/` and I load it via forman with `slackbot: ./lib/slack-bot-server`.

Do you have any suggestions on how I would do it?

Cheers

Josh

**Comment by lazyatom** [comment]
The way I handle this (with Rails) is by using the rails runner to run my server script. For example, I have the following line in my `Procfile`:
```
slack_server: bundle exec rails runner bin/slack_server
```
What this means is that my application environment is available to any bots that run, and so within the bots I can then work with records from the database using ActiveRecord. (You could also just `require "environment"` at the top of your `./lib/slack-bot-server` script, but I think this way is simpler).

This is illustrated in the ["advanced example" from the Readme](https://github.com/exciting-io/slack-bot-server#advanced-example)
```
server.on_new_token do |token|
  # Our bots need to know some data about the team they are connecting
  # to, like specifics of their account and their tasks
  team_data = Harmonia.find_team_data_by_slack_api_token(token)

  # Our bot instance stores that data in an instance variable internally
  # and then refers to it when it receives messages
  Harmonia::SlackBot.new(token: token, data: team_data)
end
```
where
`Harmonia.find_team_data_by_slack_api_token(token)` can actually be retrieving data using ActiveRecord.

Because the bots also run within this environment, inside their `on_mention` blocks they can also be loading/saving objects into the database, or interacting with other code from the app. In fact, I'd recommend that you move most of the logic about how to deal with response into objects in your app that can be tested and exercised, and then just have the bots call those methods:
```
require 'slack_bot_server/bot'
require 'my_app/bot_logic'

class MyAppBot < SlackBotServer::Bot
  on_mention do |data|
    response = MyApp::BotLogic.handle_mention(data)
    if response
      reply text: response
    end
  end
end
```
Does that help?

**Comment by lazyatom** [comment]
Closing, but feel free to re-open if you're still having problems.
